name: Polarlys Studio
favicon: null
layout_spectrum: 0.9441
typography_spectrum: 0.61917
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47609d'
    - '#000000'
    - '#005555'
    - '#000080'
    - '#404080'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
